### PR TITLE
sigmoid optimization

### PR DESCRIPTION
**Pull request by RatanRSur**
Just noticed something that is mentioned in the julia performance tips section about using consistent types could be applied to this line.

```
julia> sigmoid(x) = 1/(1+exp(-x))
sigmoid (generic function with 1 method)

julia> sigmoid_alt(x) = one(x) / (one(x) + exp(-x))
sigmoid_alt (generic function with 1 method)
```
Then I ran them each with ints and floats to make the REPL compile them before running the following:
```
julia> @time for i=1.0:0.1:100000.0
       sigmoid(i)
       end
  0.004296 seconds

julia> @time for i=1.0:0.1:100000.0
       sigmoid_alt(i)
       end
  0.003985 seconds
```

### CODE REVIEW

**Comment by tbreloff** [comment]
@RatanRSur : we're nowhere close to caring about performance optimizations (the whole package will likely be re-written several times), however there are some guidelines you should remember whenever benchmarking:

- You should always wrap your benchmarks in functions (globals will mess with your results)
- You should always "warm up" your functions before benchmarking, so that you don't test compilation time:

```
function mybenchmark(n)
  for i in 1:n
    ... do something ...
  end
end

mybenchmark(1)
@time mybenchmark(1000000)
```

**Comment by RatanRSur** [comment]
Ah, I didn't know about wrapping them in functions, I'll keep that in mind.
I did do my own version of warming them up, if you see above.
Also, why would the sigmoid function not remain in this form? The package may be rewritten many times but do you think this line is?

**Comment by Evizero** [comment]
@RatanRSur thanks for your PR!

Actually sigmoid will be rewritten as to also be dispatched and unrolled on vectors. The whole Prectictors stuff is very experimental right now. I am currently trying different things to get to a point where loss functions and predictors are nice to work with.

However, since its a reasonable change for now I'll still merge it

**Comment by RatanRSur** [comment]
Haha, ok :) I was just reading through the codebase as per Tom's suggestion and just saw an opportunity. I see that it's totally not a necessary change at this point.

**Comment by Evizero** [comment]
If you are interested in helping out further: At this point, the most helpful contributions would be informed opinions on the various topics/questions that are discussed in the issues of this package

**Comment by tbreloff** [comment]
Also don't let me discourage you from contributing PRs... I just want to make sure you're spending your time on something useful!  Optimizations are the last thing to focus on, right now we're trying to figure out the high level concepts, and we can always use multiple perspectives... head over to the issues and add your $0.02 (paypal accepted ;)

**Pull request merged**
